[versions]
kotlin = "2.3.0"
shadow = "9.3.0"
guava = "33.5.0-jre"
jda = "6.2.0"
slf4j = "2.0.9"
exposed = "1.0.0-rc-4"
mariadb = "3.5.7"
hikaricp = "7.0.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
mariadbJavaClient = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }

[bundles]
exposed = [
    "exposed-core",
    "exposed-jdbc",
    "exposed-dao"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
